/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package example;

import static java.awt.image.ImageObserver.HEIGHT;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author mdtas
 */
public class Change_PIN extends javax.swing.JFrame {

    /**
     * Creates new form Change_PIN
     */
    public Change_PIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        New_pin = new javax.swing.JTextField();
        Confirm_pin = new javax.swing.JTextField();
        Account_no = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter New PIN:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 150, 126, 27));

        jLabel2.setText("Confirm New PIN: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 187, 111, 27));

        jLabel3.setText("Enter Account Number: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 113, 141, 27));

        New_pin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        New_pin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        New_pin.setText("Enter 5 digit PIN");
        New_pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_pinMouseClicked(evt);
            }
        });
        New_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_pinActionPerformed(evt);
            }
        });
        getContentPane().add(New_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 148, 250, 31));

        Confirm_pin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Confirm_pin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(Confirm_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 185, 250, 31));

        Account_no.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Account_no.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(Account_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 111, 250, 31));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 228, 70, 45));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 228, 70, 45));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/add new patient background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        int i=0;
         try{
            FileReader Read = new FileReader(Account_no.getText()+ ".txt");
            Scanner sc = new Scanner(Read);
            
                File temp = new File("temp.txt");
                temp.createNewFile();
                FileWriter tempFile = new FileWriter("temp.txt");
      
                if(New_pin.getText().equals(Confirm_pin.getText())){
                    if(New_pin.getText().length()!= 5)
                     {
                       New_pin.setText("Please enter 5 digit PIN");
                       Confirm_pin.setText("");
                     }
                    else{
                        i=0;
                       char temp_pin[] = new char[5];
                       temp_pin = New_pin.getText().toCharArray();
                       for(i=0;i<5;i++)
                         {
                            if(temp_pin[i]<'0' || temp_pin[i]>'9')
                           {
                              New_pin.setText("Please enter 5 digit PIN");
                              Confirm_pin.setText("");
                              JOptionPane.showMessageDialog(null, "Wrong Pin Format","Error",ERROR_MESSAGE);
                              i--;
                              break;
                           }
                         }
                       if(i==5){
                           for(i=0;i<3;i++){
                           tempFile.write(sc.nextLine() + "\n");
                           }
                          tempFile.write(New_pin.getText() + "\n");
                          sc.nextLine();
                          tempFile.write(sc.nextLine() + "\n");
                          tempFile.close();
                          Read.close();
                          File old = new File(Account_no.getText()+ ".txt");
                          System.out.println(old.delete());
                          temp.renameTo(old);
                          JOptionPane.showMessageDialog(null, "Successfully changed PIN", "Message", INFORMATION_MESSAGE);
                          Account_no.setText("");
                          New_pin.setText("");
                          Confirm_pin.setText("");
                       }
                    }
                    
                }
                else{
                        JOptionPane.showMessageDialog(null, "PIN didn't match","Error", ERROR_MESSAGE);
                        temp.delete();
                     }
                
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Admin File missing", "Error", HEIGHT);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new User_dashboard().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void New_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_pinActionPerformed

    private void New_pinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_pinMouseClicked
        // TODO add your handling code here:
        New_pin.setText("");
    }//GEN-LAST:event_New_pinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_PIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Account_no;
    private javax.swing.JTextField Confirm_pin;
    private javax.swing.JTextField New_pin;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
