/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import static example.Example.accNumber;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 *
 * @author mdtas
 */

public class newAccount extends javax.swing.JFrame {

    /**
     * Creates new form newAccount
     */
    public newAccount() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        pin = new javax.swing.JTextField();
        deposit = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        acc_type = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Account Type:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 139, 36));

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 139, 36));

        jLabel3.setText("Deposit Amount:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 139, 36));

        jLabel4.setText("PIN:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 139, 36));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 235, 27));

        pin.setText("Enter 5 digit PIN");
        pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinMouseClicked(evt);
            }
        });
        getContentPane().add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 235, 27));
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 235, 27));

        enter.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        enter.setForeground(new java.awt.Color(51, 51, 255));
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, 46));

        jLabel5.setText("Fill all information correctly");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 33));

        acc_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Fixed", "Student" }));
        acc_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_typeMouseClicked(evt);
            }
        });
        acc_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_typeActionPerformed(evt);
            }
        });
        getContentPane().add(acc_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 235, 31));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 80, 46));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/add new patient background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        if(name.getText().length()==0 || deposit.getText().length()==0 || pin.getText().length()==0)
        {
            this.setVisible(true);
        }
        else{
        try{
            if(pin.getText().length()!= 5)
            {
                pin.setText("Please enter 5 digit PIN");
            }
            else{
                int i;
                char temp[] = new char[5];
                temp = pin.getText().toCharArray();
                for(i=0;i<5;i++)
                {
                    if(temp[i]<'0' || temp[i]>'9')
                    {
                         pin.setText("Please enter 5 digit PIN");
                         break;
                    }
                }
                if(i==5)
                {
                    File nfile = new File(accNumber + ".txt");
                    nfile.createNewFile();
                    FileWriter Write = new FileWriter(accNumber + ".txt");
                    Write.append(name.getText()+"\n");
                    Write.append(deposit.getText() + "\n");
                    Write.append(acc_type.getSelectedItem()+ "\n");
                    Write.append(pin.getText()+ "\n");
                    Write.append(Integer.toString(accNumber));
                    Write.close();
                    this.setVisible(false);
                    new popUp().setVisible(true); 
                }

           
            }
        
            
        }catch(IOException e)
        {
            System.out.println("An error has occured.");
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_enterActionPerformed

    private void acc_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_typeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_typeMouseClicked

    private void acc_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_typeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_acc_typeActionPerformed

    private void pinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinMouseClicked
        // TODO add your handling code here:
        pin.setText("");
    }//GEN-LAST:event_pinMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new page2().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acc_type;
    private javax.swing.JButton back;
    private javax.swing.JTextField deposit;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pin;
    // End of variables declaration//GEN-END:variables
}
