/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mdtas
 */
public class Project extends javax.swing.JFrame {

    /**
     * Creates new form Project
     */
    public Project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        forgetPass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        register = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setLocation(new java.awt.Point(100, 60));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1368, 763));
        setSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Username/Ac No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 160, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Password/PIN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 140, 27));

        userName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        userName.setText("Enter Username/Ac No");
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameMouseClicked(evt);
            }
        });
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 215, 28));

        password.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 215, 27));

        submit.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/login.png"))); // NOI18N
        submit.setText("Login as Admin");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 170, 36));

        forgetPass.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        forgetPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/icons8-lock-40.png"))); // NOI18N
        forgetPass.setText("Forget password?");
        forgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetPassActionPerformed(evt);
            }
        });
        getContentPane().add(forgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 170, 36));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/login.png"))); // NOI18N
        jButton1.setText("Login as User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 170, 36));

        register.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/icons8-register-25.png"))); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 110, 35));

        Close.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/Close.png"))); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 110, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/login Background final.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(1368, 768));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, -1, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String user = userName.getText();
        String pass = password.getText();
        try {
            FileReader Read = new FileReader(user +".txt");
            Scanner sc = new Scanner(Read);
            String admin = sc.nextLine();
            String pa = sc.nextLine();
            if(pass.equals(pa))
           {
             new page2().setVisible(true);
             this.setVisible(false);
          }
           else
          {
            JOptionPane.showMessageDialog(null,"Invalid Password or Username");
          }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Wrong Username");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void forgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetPassActionPerformed
        // TODO add your handling code here:
        new forgetPassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_forgetPassActionPerformed

    private void userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseClicked
        // TODO add your handling code here:
        userName.setText("");
    }//GEN-LAST:event_userNameMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new register_admin().setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            FileReader read = new FileReader(userName.getText()+".txt");
            Scanner sc = new Scanner(read);
            String pass = null;
            for(int i=0;i<4;i++)
            {
                pass = sc.nextLine();
            }
            read.close();
            if(pass.equals(password.getText()))
            {
                this.setVisible(false);
                new User_dashboard().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Wrong Password or Username", "Error", HEIGHT);
            }
        }catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, "Wrong Password or Username", "Error", HEIGHT);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to Close the apllication","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton forgetPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JButton submit;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
