/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author mdtas
 */
public class withdraw extends javax.swing.JFrame {

    /**
     * Creates new form withdraw
     */
    public withdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        withAmount = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter Account Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 88, 157, 35));

        jLabel2.setText("Withdraw Amount:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 144, 137, 33));

        account.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 257, 31));

        withAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        withAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withAmountMouseClicked(evt);
            }
        });
        getContentPane().add(withAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 257, 31));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, 44));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 80, 44));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/example/add new patient background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        if(account.getText().length()==0 || withAmount.getText().length()==0 || account.getText().equals("Enter Account Number") || withAmount.getText().equals("Enter Withdraw Amount"))
        {
            account.setText("Enter Account Number");
            withAmount.setText("Enter Withdraw Amount");
        }
        else
        {
            try{ 
            File inputFile = new File(account.getText() + ".txt");
            FileReader myfile = new FileReader(inputFile);
            Scanner sc = new Scanner(myfile);
            String temp = null;
            int i=0,balance = 0,withdraw;
            //balance check
            String name=sc.nextLine();
            String bal = sc.nextLine();
            balance = Integer.parseInt(bal);
            withdraw = Integer.parseInt(withAmount.getText());
            balance -= withdraw;
            if(balance<500)
            {
                JOptionPane.showMessageDialog(null, "Balance less than 500.Operation failed", "Error", ERROR_MESSAGE);
            }
            else{
            File tempF = new File("temp.txt");
            tempF.createNewFile();
            FileWriter tempFile = new FileWriter(tempF);
            tempFile.append(name + "\n");
            tempFile.append(balance + "\n");
            for(i=0;i<3;i++)
            {
                temp = sc.nextLine();
                tempFile.append(temp + "\n");
            }
            myfile.close();
            tempFile.close();
            inputFile.delete();
            File newF = new File(account.getText() + ".txt");
            tempF.renameTo(newF);
            JOptionPane.showMessageDialog(null, "Successful.Your account balance:"+ String.valueOf(balance), "Balance", INFORMATION_MESSAGE);
            withAmount.setText("");
            }
            
        }catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, "Account not found", "Error", ERROR_MESSAGE);
        }
            
        }

    }//GEN-LAST:event_okActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new page2().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:
        account.setText("");
    }//GEN-LAST:event_accountMouseClicked

    private void withAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withAmountMouseClicked
        // TODO add your handling code here:
        withAmount.setText("");
    }//GEN-LAST:event_withAmountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton ok;
    private javax.swing.JTextField withAmount;
    // End of variables declaration//GEN-END:variables
}
